### ISSUE TITLE
Path is not returned to command line in OS X 10.10+iTerm2

### ISSUE THREAD

**Issue by ravi** [pindexis/qfc#19]
Searching using ctrl-F works perfectly, but pressing Enter/Return returns to the command line without appending the path to the command line. My environment is OS X 10.10 + iTerm2 + bash(3.2.57).

**Comment by pindexis** [comment]
Bash 4.x+ is required for qfc to work.
http://apple.stackexchange.com/a/24635

**Comment by ravi** [comment]
Ah, sorry I should have noticed/checked the bash version requirement. Thank you.
